extensions:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  health_check: 
service:
  pipelines:
    traces:
      exporters:
      - azuremonitor
      - logging
      receivers:
      - zipkin
  extensions:
  - pprof
  - zpages
  - health_check
receivers:
  zipkin: 
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    maxbatchinterval: 5s
    instrumentation_key: ''
    maxbatchsize: 5

