apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub1
auth:
  secretStore: strongbox  
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: serviceBusEndpoint
