apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
auth:
  secretStore: strongbox
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    secretKeyRef:
      name: storageAccountName
  - name: accountKey
    secretKeyRef:
      name: storageAccountKey
  - name: tableName
    value: orders
