apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
auth:
  secretStore: strongbox
spec:
  type: state.aws.dynamodb
  version: v1
  metadata:
  - name: table
    value: dapr_store
  - name: region
    value: us-east-2