# Use this command to run local
# Use fileName for the local store
# ./demo.ps1
# @itemName = fileName

# Use this command to run in the cloud
# Use blobName for the local store
# ./demo.ps1 -env azure
@itemName = blobName


POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "create",
    "data": "Hello World",
    "metadata": {
        "{{itemName}}": "myTestFile.txt"
    }
}

###

POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "list"
}

###

POST http://localhost:3500/v1.0/bindings/files

{
    "operation": "get",
    "metadata": {
        "{{itemName}}": "myTestFile.txt"
    }
}

###

POST http://localhost:3500/v1.0/bindings/files/

{
    "operation": "delete",
    "metadata": {
        "{{itemName}}": "myTestFile.txt"
    }
}
