receivers:
  zipkin: 
extensions:
  health_check: 
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  pipelines:
    traces:
      receivers:
      - zipkin
      exporters:
      - azuremonitor
      - logging
  extensions:
  - pprof
  - zpages
  - health_check
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    maxbatchinterval: 5s
    instrumentation_key: e755f218-c26e-4602-bfeb-b6b3ebdd7824
    maxbatchsize: 5

