receivers:
  zipkin:
    endpoint: 0.0.0.0:9411
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    instrumentation_key: "51c4f15a-149d-4d99-8021-8d43cd5af780"
    # maxbatchsize is the maximum number of items that can be
    # queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling
    # the configured endpoint.
    maxbatchinterval: 10s
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [azuremonitor,logging]