receivers:
  zipkin:
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    instrumentation_key: ""
    # max batch size is the maximum number of items that can be
    # queued before calling to the configured endpoint
    maxbatchsize: 5
    # max batch interval is the maximum time to wait before calling
    # the configured endpoint.
    maxbatchinterval: 5s
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [azuremonitor,logging]