# Use this command to run local
# ./demo.ps1

# Use this command to run in the cloud
# ./demo.ps1 -env azure

POST http://localhost:3500/v1.0/state/statestore

[
    {
        "key": "Dog",
        "value": "Hybrid"
    }
]

###

http://localhost:3500/v1.0/state/statestore/Dog

###

DELETE http://localhost:3500/v1.0/state/statestore/Dog