# dapr run --app-id local --dapr-http-port 3500
# dapr run --app-id cloud --dapr-http-port 3500 --components-path ./azureComponets

POST http://localhost:3500/v1.0/state/statestore

[
    {
        "key": "Dog",
        "value": "Hybrid"
    }
]

###

http://localhost:3500/v1.0/state/statestore/Dog

###

DELETE http://localhost:3500/v1.0/state/statestore/Dog