apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secrets-store
auth:
  secretStore: strongbox  
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    secretKeyRef:
      name: VAULTNAME
  - name: azureTenantId
    secretKeyRef:
      name: TENANT
  - name: azureClientId
    secretKeyRef:
      name: APPID
  - name: azureClientSecret
    secretKeyRef:
      name: PASSWORD