apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secrets-store
auth:
  secretStore: strongbox
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    secretKeyRef:
      name: AZURE_KEY_VAULT_NAME
  - name: azureTenantId
    secretKeyRef:
      name: AZURE_TENANT
  - name: azureClientId
    secretKeyRef:
      name: AZURE_APP_ID
  - name: azureClientSecret
    secretKeyRef:
      name: AZURE_PASSWORD