apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secrets-store
auth:
  secretStore: strongbox  
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
  - name: region
    value: us-east-2
  - name: accessKey
    secretKeyRef:
      key: accessKey
      name: accessKey
  - name: secretKey
    secretKeyRef:
      key: secretKey
      name: secretKey
