apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: files
auth:
  secretStore: strongbox
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    secretKeyRef:
      key: acct
      name: acct
  - name: storageAccessKey
    secretKeyRef:
      key: key
      name: key
  - name: container
    value: container1
  - name: decodeBase64
    value: false
  - name: getBlobRetryCount
    value: 3