# Use this command to run local
# ./demo.ps1

# Use this command to run in the cloud
# ./demo.ps1 -cloud

POST http://localhost:3500/v1.0/publish/pubsub/neworder
Content-Type: application/json

{"orderId":"44"}

###

GET http://localhost:3500/v1.0/invoke/app1/method/order