# Use this command to run local
# dapr run -a app1 -p 5013 -H 3500 -d ./components -- dotnet run --project ./src/

POST http://localhost:3500/v1.0/publish/pubsub/new
Content-Type: application/json

{
    "data": "Hello World"
}