# Use this command to run local
# ./demo.ps1

# Use this command to run in the azure
# ./demo.ps1 -env azure

# Use this command to run in the aws
# ./demo.ps1 -env aws

http://localhost:3500/v1.0/secrets/my-secrets-store/dapr-secret
